# Generated by Django 4.1.5 on 2023-01-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_project1app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updates',
            new_name='updated',
        ),
    ]
